# Generated by Django 2.2.7 on 2019-12-05 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Age',
            field=models.CharField(choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Location',
            field=models.CharField(choices=[('Ground_Plane', 'Ground_Plane'), ('Above_Ground', 'Above_Ground'), ('Other', 'Other')], default='Other', max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Other_Activities',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Specific_Location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Unique_Squirrel_ID',
            field=models.CharField(max_length=100),
        ),
    ]
